export type PostStatus = "draft" | "published";

// Matches the posts table exactly
export interface Post {
  id: string;
  user_id: string;
  title: string;
  slug: string | null;
  excerpt: string | null;
  content: string;
  cover_image: string | null;
  status: PostStatus;
  published_at: string | null;
  created_at: string;
  updated_at: string;
  // Draft fields — staged changes for published posts
  draft_title: string | null;
  draft_content: string | null;
  draft_excerpt: string | null;
  draft_cover_image: string | null;
  draft_tags: string[] | null;
  draft_categories: string[] | null;
  has_pending_changes: boolean;
  publish_at: string | null;
}

// For creating a new post (id, created_at, updated_at are generated by the DB)
export type CreatePost = Omit<Post, "id" | "created_at" | "updated_at">;

// For updating a post (everything is optional except you need at least one field)
export type UpdatePost = Partial<
  Omit<Post, "id" | "user_id" | "created_at" | "updated_at">
>;
